### ISSUE TITLE
Missing "transitionToExternal" hook in Route override

### ISSUE THREAD

**Issue by huiyuan** [trentmwillis/ember-engines#1]
There should be a `transitionToExternal` function in `-private/route-ext.js`, something like this

``` javascript
transitionToExternal() {
  let router = this.router;
  return router.transitionToExternal(...arguments);
}
```

**Comment by trentmwillis** [comment]
I imagine this will also need to happen with `Route#replaceWith`. Will update in a bit.

**Comment by trentmwillis** [comment]
This should be fixed now. Trying pulling the `links` branch again.
