### ISSUE TITLE
Incorrect context when calling "getExternalRoute" 

### ISSUE THREAD

**Issue by huiyuan** [trentmwillis/ember-engines#2]
This might not be an issue introduced by this fork, but since I found it in its related function, report an issue here.

I added the `transitionToExternal` in `-private/router-ext.js` for testing purpose, and when `getExternalRoute` gets called, its `this` context is application instead of an engine instance, as a result, `this._externalRoutes` is always undefined.

**Comment by trentmwillis** [comment]
After glancing over my implementation again, this is my fault. We call `getOwner` on the Router, which comes from the application, so it is actually making sense. I'll need to think of a way around that.

**Comment by trentmwillis** [comment]
Updated this and I believe it should work. You can't call `transitionToExternal` on Router anymore, but I don't think you should anyway, so that should be a non-issue.
